# Generated by Django 3.2.7 on 2021-09-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelfModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=100)),
                ('Inshelf', models.BooleanField(default=True)),
            ],
        ),
    ]
